<a href="https://colab.research.google.com/github/Malathicse/Datascience/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7fc6cfc5c440>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
zero_array=np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
zero_array.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
fifth=np.zeros(10)
fifth[4]=1
fifth

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
value=np.arange(10,50)
value

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
value[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
matrix_1=np.arange(0,9).reshape(3,3)
matrix_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
array_1=np.array([1,2,0,0,4,0])
print(np.nonzero(array_1))
array_1

(array([0, 1, 4]),)


array([1, 2, 0, 0, 4, 0])

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
ide=np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
np.random.random((3,3,3))

array([[[0.13850491, 0.36322791, 0.41238757],
        [0.54474131, 0.51778866, 0.72661155],
        [0.39223659, 0.78833515, 0.77590109]],

       [[0.00417101, 0.30015591, 0.48812743],
        [0.82940754, 0.06142175, 0.81718863],
        [0.86521473, 0.77964895, 0.71257033]],

       [[0.98347667, 0.36828859, 0.34353592],
        [0.52540459, 0.94109646, 0.92304195],
        [0.54500724, 0.62718658, 0.01562112]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
a=np.random.random((10,10,10))
mini=np.min(a)
maxi=np.max(a)
print("min: ",mini,"max: ",maxi)

min:  0.0004707883166097382 max:  0.9991164796757478


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
A=np.random.random(30)
mean_value=np.mean(A)
mean_value

0.5951323577621781

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
A=np.ones((10,10))
A[1:-1,1:-1]=0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [18]:
z=np.ones((10,10))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [19]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [20]:
z=np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [21]:
z=np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [22]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [23]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [24]:
z=np.random.random((5,5))
zmin=z.min()
zmax=z.max()
z=((z-zmin)/(zmax-zmin))
z

array([[0.53988646, 0.55812101, 0.01974273, 0.        , 0.59721751],
       [0.56838886, 0.82905333, 1.        , 0.05503974, 0.14189058],
       [0.30379837, 0.9867898 , 0.83166897, 0.73971961, 0.86439754],
       [0.59221515, 0.07306763, 0.94327462, 0.59256577, 0.30949665],
       [0.53822671, 0.0075711 , 0.31811538, 0.87349612, 0.23310552]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [25]:
z=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [26]:
z=np.ones((5,3))@np.ones((3,2))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
z=np.arange(20)
z[(z>3)&(z<=8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)

[     0      1      2      4      0      0      0      0      0    256
    512   1024   2048   4096   8192  16384  32768  65536 131072 262144]
[False False False False  True  True  True  True  True False False False
 False False False False False False False False]
[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
 -0. -8.j  0. +9.j  0.+10.j  0.+11.j  0.+12.j  0.+13.j  0.+14.j  0.+15.j
  0.+16.j  0.+17.j  0.+18.j  0.+19.j]
[ 0.  1.  2.  3. -4. -5. -6. -7. -8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [31]:
z = np.random.uniform(-10,+10,10)

print (np.copysign(np.ceil(np.abs(z)),z))

[ -2.  10.  -5.   5.  -5.  -6.   4.   7. -10.   5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [32]:
z=np.arange(10)
x=np.arange(3)
y=np.intersect1d(z,x)
y

array([0, 1, 2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [33]:
z=np.seterr(all="ignore")
x=np.ones(1)/0
x
y=np.errstate(divide="ignore")
x

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [35]:
y=np.datetime64('today','D')-np.timedelta64(1,'D')
t=np.datetime64('today','D')
to=np.datetime64('today','D')+np.timedelta64(1,'D')
print(y)
print(t)
print(to)

2022-05-23
2022-05-24
2022-05-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [36]:
y=np.arange('2022-07','2022-08',dtype='datetime64[D]')
y

array(['2022-07-01', '2022-07-02', '2022-07-03', '2022-07-04',
       '2022-07-05', '2022-07-06', '2022-07-07', '2022-07-08',
       '2022-07-09', '2022-07-10', '2022-07-11', '2022-07-12',
       '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
       '2022-07-17', '2022-07-18', '2022-07-19', '2022-07-20',
       '2022-07-21', '2022-07-22', '2022-07-23', '2022-07-24',
       '2022-07-25', '2022-07-26', '2022-07-27', '2022-07-28',
       '2022-07-29', '2022-07-30', '2022-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [37]:
a=np.ones(4)*1
b=np.ones(4)*2
c=np.ones(4)*3
z=np.add(a,b,out=b)
x=np.negative(a,out=a)
c=np.multiply(a,b,out=a)
v=np.divide(a,2,out=a)
print(z)
print(x)
print(c)
print(v)

[3. 3. 3. 3.]
[-1.5 -1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
z=np.random.uniform(0,10,20)
print(z)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[0.94909361 7.7389958  7.66651169 4.0634112  2.76670342 9.51016681
 1.13478808 5.05661501 9.7562999  1.93541524 6.09280987 8.06235865
 4.75478884 9.58629728 2.307142   8.02778358 3.02771319 2.25371967
 7.30373493 2.1839347 ]
[0. 7. 7. 4. 2. 9. 1. 5. 9. 1. 6. 8. 4. 9. 2. 8. 3. 2. 7. 2.]
[0. 7. 7. 4. 2. 9. 1. 5. 9. 1. 6. 8. 4. 9. 2. 8. 3. 2. 7. 2.]
[0. 7. 7. 4. 2. 9. 1. 5. 9. 1. 6. 8. 4. 9. 2. 8. 3. 2. 7. 2.]
[0 7 7 4 2 9 1 5 9 1 6 8 4 9 2 8 3 2 7 2]
[0. 7. 7. 4. 2. 9. 1. 5. 9. 1. 6. 8. 4. 9. 2. 8. 3. 2. 7. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:

z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [40]:
def generator():
 for i in range(10):
   yield i
z=np.fromiter(generator(),dtype=float,count=-1)
z  

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
z=np.linspace(0,1,num=12)[1:-1]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
z=np.random.random(10)
z.sort()
z

array([0.09057179, 0.13371864, 0.22304739, 0.37872702, 0.41112122,
       0.41785629, 0.52480129, 0.58090766, 0.60391018, 0.84941779])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [43]:
z=np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [44]:
a=np.random.randint(1,5)
b=np.random.randint(1,5)
z=np.allclose(a,b)
print(z)
z=np.array_equal(a,b)
print(z)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [45]:
z=np.ones(10)
z.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [46]:
z=np.random.random((10,20))
x,c=z[:,0],z[:,1]
a=np.sqrt(x**2+c**2)
print(a)
b=np.arctan2(x,c)
print(b)

[0.9293959  0.91147626 0.74104365 0.43767907 0.88185439 0.69836282
 0.55832571 0.6117465  0.58205084 0.81069521]
[0.02271544 0.66069144 0.03121175 0.15877018 1.00593954 0.58432861
 0.68538567 0.41705421 0.50363416 1.21997824]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [47]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.66488642 0.56585744 0.7764765  0.04820639 0.68378285 0.
 0.48092298 0.35349215 0.80451136 0.98660787]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [48]:
z=np.zeros((5,5),[('x','float'),('y','float')])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,num=5),np.linspace(0,1,num=5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [49]:
z=np.arange(10)
x=z+1.5
c=1/np.subtract.outer(z,x)
print(np.linalg.det(c))

-85.11762642807601


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [50]:
for dtype in [np.int16,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float16,np.float32,np.float64]:
  print(np.finfo(dtype).min) 
  print(np.finfo(dtype).max) 
  print(np.finfo(dtype).eps)

-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [51]:
np.set_printoptions(threshold=np.sys.maxsize)
z=np.ones((16,16))
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [52]:
z=np.arange(100)
v=np.random.uniform(0,100)
i=(np.abs(z-v)).argmin()
print(z[i])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [53]:
z=np.zeros(10,[('position',[('x',float),('y',float)]),('color',[('r',float),('g',float),('b',float)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.65010646 0.16061929 0.65288702 0.15997617 0.707846
  0.41834339 0.42638765 0.38991759 0.6031632 ]
 [0.65010646 0.         0.49631916 0.13164449 0.80993075 0.33599318
  0.33165644 0.57328231 0.34293291 0.70557067]
 [0.16061929 0.49631916 0.         0.51366534 0.31691607 0.60007522
  0.31497525 0.41424142 0.28670695 0.60496436]
 [0.65288702 0.13164449 0.51366534 0.         0.81134662 0.20434883
  0.26998306 0.48956539 0.29045618 0.59912142]
 [0.15997617 0.80993075 0.31691607 0.81134662 0.         0.85506181
  0.56863438 0.53003695 0.5409198  0.68488013]
 [0.707846   0.33599318 0.60007522 0.20434883 0.85506181 0.
  0.29009248 0.41295239 0.31882487 0.46077755]
 [0.41834339 0.33165644 0.31497525 0.26998306 0.56863438 0.29009248
  0.         0.2462001  0.02880283 0.40551633]
 [0.42638765 0.57328231 0.41424142 0.48956539 0.53003695 0.41295239
  0.2462001  0.         0.24477598 0.19120262]
 [0.38991759 0.34293291 0.28670695 0.29045618 0.5409198  0.31882487
  0.02880283 0.2447759

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [55]:
Z = np.arange(10, dtype=np.int32)

Z = Z.astype(np.float32, copy=False)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n6, , , 7, 8\n, , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [57]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [58]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [59]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [60]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.35577608 -0.52182595 -0.07704801  0.21932849 -0.03605303 -0.00364217
   0.3646251  -0.04261855  0.04365628 -0.30219824]
 [-0.03276488  0.23603859 -0.01199412  0.4361361  -0.09218167 -0.05097728
  -0.05910804  0.37313295 -0.29599853 -0.50228314]
 [-0.46371831 -0.16886363 -0.30239076  0.1392722   0.37501357 -0.06539748
   0.20056246 -0.04785875  0.24720659  0.0861741 ]
 [ 0.31385048  0.19898548 -0.08042819 -0.46619438 -0.18199899  0.1874994
   0.43937723  0.3359241  -0.37918618 -0.36782894]
 [-0.29770872 -0.16469982  0.04243963  0.51729884  0.03725624 -0.11305117
  -0.12589566 -0.13035769 -0.22850835  0.46322671]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [61]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 4 8]
 [6 7 3]
 [2 1 1]]
[[2 1 1]
 [5 4 8]
 [6 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [62]:
Z = np.random.randint(0,3,(3,10))

print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [63]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5773767753097527


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [64]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for x,y,z in it: 
  z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [68]:
class NamedArray(np.ndarray):
   def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

   def __array_finalize__(self, obj):
      if obj is None: 
       return
      self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [69]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 1. 4. 4. 3. 2. 2. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [70]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [71]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [72]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[59 49 59 65]
 [49 57 71 64]
 [63 52 43 59]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [73]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.68894493 0.52527497 0.53045809 0.42321473 0.52723448 0.61132394
 0.55387865 0.64279673 0.56345111 0.66371794]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [74]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
z= np.diag(np.dot(a,b))
z

array([1.17172771, 1.00281611, 1.72407236, 1.77824218, 1.49779888])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [75]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [76]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [77]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [78]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 47) ( 1, 48) ( 4,  6) ( 4, 53) ( 6, 53) ( 7, 30) ( 7, 69) (10, 46)
 (10, 90) (30, 69) (43, 72) (43, 80) (43, 92) (43, 98) (46, 90) (47, 48)
 (55, 78) (55, 81) (58, 67) (58, 72) (67, 72) (72, 92) (77, 96) (77, 99)
 (78, 81) (80, 98) (81, 82) (81, 97) (82, 97) (96, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [80]:
def moving_average(a, n=3) :
 ret = np.cumsum(a, dtype=float)
 ret[n:] = ret[n:] - ret[:-n]
 return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [81]:
from numpy.lib import stride_tricks
def rolling(a, window):
 shape = (a.size - window + 1, window)
 strides = (a.itemsize, a.itemsize)
 return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [82]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.14449487,  0.07241584, -0.71800201, -0.56987622, -0.42448098,
       -0.91857093, -0.91761452, -0.1360879 , -0.35174161, -0.61418667,
       -0.89553747,  0.36107917, -0.18700213,  0.58750257, -0.20606626,
        0.1342861 , -0.21997582,  0.41707095,  0.89033329,  0.15859983,
        0.37548087,  0.26786617,  0.27563243,  0.45917442, -0.6023285 ,
        0.58076082, -0.96015176,  0.8613074 , -0.72664543, -0.52921483,
       -0.4632255 , -0.20516962, -0.74146762, -0.23851346, -0.62669604,
        0.63722442, -0.97550256,  0.02761234, -0.41050863,  0.00257057,
       -0.87965501,  0.09250768, -0.1229693 ,  0.84091373,  0.30837919,
        0.09846754,  0.51657656,  0.07360922, -0.22859219, -0.5582426 ,
       -0.70436398, -0.27376024,  0.58342087, -0.02786985, -0.83313132,
        0.59940141,  0.14229872,  0.34701997,  0.48478954,  0.50051186,
       -0.35661124, -0.0046173 , -0.64395132,  0.94764428,  0.4901635 ,
        0.88280091, -0.08109675, -0.07026305,  0.66790146, -0.26

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [83]:
def distance(P0, P1, p):
 T = P1 - P0
 L = (T**2).sum(axis=1)
 U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
 U = U.reshape(len(U),1)
 D = P0 + U*T - p
 return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.0742142   9.45728783 11.2344353  13.66399819  2.01987941  5.1034753
 13.50444124  8.78890455  3.53435931 12.25681869]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [85]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))
 


[[8.54421145e+00 5.06370625e+00 1.13400087e+01 1.58446898e+01
  1.02169647e+01 5.73948658e+00 8.05233509e+00 7.60806142e-02
  9.20883204e+00 5.91766770e+00]
 [4.61063120e-01 5.41481409e+00 1.24846714e+01 7.14243691e+00
  9.58387877e-01 1.47554549e+01 1.14578852e+00 5.84563580e+00
  2.79695656e-01 4.00721093e+00]
 [6.84554375e-01 2.55735661e+00 5.86037820e+00 8.07424434e+00
  4.34473021e+00 6.19353971e+00 4.03772243e-01 2.49519333e+00
  1.48774639e+00 4.29471047e+00]
 [7.26257673e+00 3.07454217e-01 7.57561636e-02 2.42900270e-01
  1.40801728e+00 6.34498035e+00 7.28197598e+00 5.39788952e+00
  6.28369644e+00 2.95080345e+00]
 [1.99894738e-01 4.59959219e+00 1.11434123e+01 6.58129107e+00
  7.85245884e-01 1.36834841e+01 1.61601453e+00 4.53678868e+00
  2.41244679e-01 3.07161751e+00]
 [4.75499948e+00 7.43530886e+00 5.62612986e+00 1.24205784e+01
  9.71311662e+00 2.08479508e+00 4.96846177e+00 4.97595211e+00
  5.93432059e+00 8.87595518e+00]
 [2.18905883e+00 3.58907856e+00 2.18520547e+00 5.40851944e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [86]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 4 7 5 0 4 9 0 6 9]
 [9 2 4 9 9 7 5 8 4 2]
 [7 8 4 7 2 7 9 6 6 9]
 [3 4 1 7 9 6 3 3 1 0]
 [5 1 0 0 1 3 1 4 8 8]
 [2 8 8 2 7 4 8 0 3 5]
 [1 6 3 0 7 6 0 1 0 0]
 [8 4 3 1 8 0 4 6 7 3]
 [2 9 8 8 5 0 3 7 8 6]
 [8 2 9 2 1 3 1 9 2 7]]
[[0 0 0 0 0]
 [0 5 4 7 5]
 [0 9 2 4 9]
 [0 7 8 4 7]
 [0 3 4 1 7]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [87]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [88]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [89]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [90]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 1]
   [1 3 4]
   [0 1 1]]

  [[2 1 4]
   [3 4 3]
   [1 1 4]]

  [[1 4 2]
   [4 3 0]
   [1 4 1]]

  [[4 2 2]
   [3 0 3]
   [4 1 3]]

  [[2 2 3]
   [0 3 1]
   [1 3 2]]

  [[2 3 4]
   [3 1 2]
   [3 2 3]]

  [[3 4 0]
   [1 2 3]
   [2 3 3]]

  [[4 0 3]
   [2 3 3]
   [3 3 0]]]


 [[[1 3 4]
   [0 1 1]
   [1 1 4]]

  [[3 4 3]
   [1 1 4]
   [1 4 0]]

  [[4 3 0]
   [1 4 1]
   [4 0 1]]

  [[3 0 3]
   [4 1 3]
   [0 1 0]]

  [[0 3 1]
   [1 3 2]
   [1 0 4]]

  [[3 1 2]
   [3 2 3]
   [0 4 2]]

  [[1 2 3]
   [2 3 3]
   [4 2 2]]

  [[2 3 3]
   [3 3 0]
   [2 2 1]]]


 [[[0 1 1]
   [1 1 4]
   [2 4 1]]

  [[1 1 4]
   [1 4 0]
   [4 1 2]]

  [[1 4 1]
   [4 0 1]
   [1 2 3]]

  [[4 1 3]
   [0 1 0]
   [2 3 3]]

  [[1 3 2]
   [1 0 4]
   [3 3 1]]

  [[3 2 3]
   [0 4 2]
   [3 1 1]]

  [[2 3 3]
   [4 2 2]
   [1 1 1]]

  [[3 3 0]
   [2 2 1]
   [1 1 3]]]


 [[[1 1 4]
   [2 4 1]
   [1 2 4]]

  [[1 4 0]
   [4 1 2]
   [2 4 2]]

  [[4 0 1]
   [1 2 3]
   [4 2 3]]

  [[0 1 0]
   [2 3 3]
   [2 3 4]]

  [[1 0 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [91]:
class Symetric(np.ndarray):
 def __setitem__(self, index, value):
  i,j = index
  super(Symetric, self).__setitem__((i,j), value)
  super(Symetric, self).__setitem__((j,i), value)
 def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
  S = symetric(np.random.randint(0,10,(5,5)))
  S[2,3] = 42
print(S)

[4.87140949e+00 1.48439679e+00 1.14839578e+00 1.02255885e+00
 7.72303443e-01 5.76922346e-01 4.92597279e-01 3.63222058e-01
 1.98466599e-01 2.91294320e-03]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [92]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [93]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [94]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
  Z[1:-1,0:-2] + Z[1:-1,2:] +
  Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
  birth = (N==3) & (Z[1:-1,1:-1]==0)
  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...] = 0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100):
   Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [95]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [96]:
def cartesian(arrays):
   arrays = [np.asarray(a) for a in arrays]
   shape = (len(x) for x in arrays)
   ix = np.indices(shape, dtype=int)
   ix = ix.reshape(len(arrays), -1).T
   for n, arr in enumerate(arrays):
       ix[:, n] = arrays[n][ix[:, n]]
       return ix
print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [97]:
Z = np.array([("Hello", 2.5, 3),
("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [98]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.39 s per loop
10 loops, best of 5: 183 ms per loop
10 loops, best of 5: 145 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [99]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [100]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 4 1]
 [0 2 0]
 [3 1 2]
 [0 2 4]
 [0 0 1]
 [1 2 3]
 [2 1 4]
 [1 2 1]
 [3 2 1]
 [0 2 3]]
[[1 4 1]
 [0 2 0]
 [3 1 2]
 [0 2 4]
 [0 0 1]
 [1 2 3]
 [2 1 4]
 [1 2 1]
 [3 2 1]
 [0 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [101]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [102]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [103]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A) # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B) # np.inner(A, B)
np.einsum('i,j', A, B) # np.outer(A, B)

array([[0.27348185, 0.30901205, 0.23483364, 0.37405678, 0.01243164,
        0.01175798, 0.13675572, 0.08772094, 0.14377736, 0.23468992],
       [0.51309719, 0.57975772, 0.44058675, 0.7017924 , 0.02332382,
        0.02205992, 0.25657635, 0.16457899, 0.2697501 , 0.44031712],
       [0.45462488, 0.5136888 , 0.39037769, 0.62181647, 0.02066585,
        0.01954598, 0.22733703, 0.14582365, 0.23900951, 0.39013878],
       [0.38088037, 0.43036356, 0.32705469, 0.52095188, 0.01731365,
        0.01637544, 0.19046079, 0.12216965, 0.20023988, 0.32685454],
       [0.17060015, 0.19276417, 0.14649109, 0.23333959, 0.00775496,
        0.00733472, 0.0853093 , 0.05472102, 0.08968946, 0.14640144],
       [0.20072196, 0.22679934, 0.17235611, 0.27453891, 0.0091242 ,
        0.00862977, 0.10037184, 0.06438277, 0.10552537, 0.17225063],
       [0.21756892, 0.24583502, 0.18682227, 0.29758146, 0.00989001,
        0.00935408, 0.10879623, 0.06978653, 0.1143823 , 0.18670794],
       [0.40611097, 0.45887207, 0.3487197

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [104]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [105]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [106]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.27294283  0.083119  ]
